[package]
name = "compress-tools"
version = "0.6.0"
authors = ["Jonathas-Conceicao <jadoliveira@inf.ufpel.edu.br>"]
description = "Utility functions for compressed and archive files handling"
repository = "https://github.com/OSSystems/compress-tools-rs"
homepage = "https://github.com/OSSystems/compress-tools-rs"
documentation = "https://docs.rs/compress-tools"
keywords = ["compression", "archive"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
build = "src/build.rs"

[badges]
coveralls = { repository = "ossystems/compress-tools-rs" }

[dependencies]
derive_more = { version = "0.99", default-features = false, features = ["display", "from", "error"] }
futures = { version = "0.3.5", optional = true }
tokio = { version = "0.2.22", optional = true }

[features]
async = ["futures", "tokio"]

[dev-dependencies]
tempfile = "3.1"
argh = "0.1"
tokio = { version = "0.2.22", features = ["macros", "fs"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
vcpkg = "0.2"

[target.'cfg(not(target_os = "windows"))'.build-dependencies]
pkg-config = "0.3"