[package]
name = "compress-tools"
version = "0.4.0"
authors = ["Jonathas-Conceicao <jadoliveira@inf.ufpel.edu.br>"]
description = "Utility functions for compressed and archive files handling"
repository = "https://github.com/OSSystems/compress-tools-rs"
homepage = "https://github.com/OSSystems/compress-tools-rs"
documentation = "https://docs.rs/compress-tools"
keywords = ["compression", "archive"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
build = "src/build.rs"

[badges]
coveralls = { repository = "ossystems/compress-tools-rs" }

[dependencies]
derive_more = { version = "0.99.5", default-features = false, features = ["display", "from", "error"] }

[build-dependencies]
pkg-config = "0.3.17"

[dev-dependencies]
tempfile = "3.1.0"
argh = "0.1.3"
