name: CI - Windows - x86_64

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.44.0 # MSRV
          - stable
          - nightly

    name: Test ${{ matrix.version }} - x86_64-pc-windows-msvc
    runs-on: windows-latest

    steps:
      - name: Install Dependencies
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: "libarchive"
          vcpkgTriplet: x64-windows
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
          # run-vcpkg action needs to have a pinned down version of vcpkg
          # this commit id refferes to the vcpkg version 2021.xx
          vcpkgGitCommitId: acb6b10e7fdf5e8519c18398d0b069e1d58ca025

      - name: Test vcpkg
        run: |
          vcpkg list
          vcpkg search libarchive
          vcpkg search libarchive --triplet x64-windows
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-pc-windows-msvc
          profile: minimal
          override: true

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.version }}-x86_64-pc-windows-msvc-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ matrix.version }}-x86_64-pc-windows-msvc-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.version }}-x86_64-pc-windows-msvc-cargo-build-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Check build
        uses: actions-rs/cargo@v1
        env:
          OPENSSL_ROOT_DIR: "D:\\a\\compress-tools\\vcpkg\\installed\\x64-windows"
          VCPKGRS_DYNAMIC: 1
        with:
          command: check
          args: --release --all --bins --examples --tests

      - name: Tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        env:
          OPENSSL_ROOT_DIR: "D:\\a\\compress-tools\\vcpkg\\installed\\x64-windows"
          VCPKGRS_DYNAMIC: 1
        with:
          command: test
          args: --release --all --all-features --no-fail-fast -- --nocapture

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
